on:
  push:
    tags:
      - "*"

jobs:
  publish-mac:
    name: Publish release (macOS)
    runs-on: macos-latest
    steps:
      - name: Initialize Java
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Publish release
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: publish --no-daemon
        env:
          SIGNING_PGP_KEY: ${{ secrets.SIGNING_PGP_KEY }}
          SIGNING_PGP_PASSWORD: ${{ secrets.SIGNING_PGP_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}

  publish-windows:
    name: Publish release (Windows)
    runs-on: windows-latest
    steps:
      - name: Initialize Java
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Publish release
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: publish --no-daemon
        env:
          SIGNING_PGP_KEY: ${{ secrets.SIGNING_PGP_KEY }}
          SIGNING_PGP_PASSWORD: ${{ secrets.SIGNING_PGP_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}

  publish-linux:
    name: Publish release (Linux)
    runs-on: ubuntu-latest
    steps:
      - name: Extract version from tag
        uses: olegtarasov/get-tag@v2.1
        id: get_version
        with:
          tagRegex: "v(.*)"

      - name: Initialize Java
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Initialize QEMU
        uses: docker/setup-qemu-action@v1

      - name: Initialize buildx
        uses: docker/setup-buildx-action@v1

      - name: Publish release
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: publish --no-daemon
        env:
          SIGNING_PGP_KEY: ${{ secrets.SIGNING_PGP_KEY }}
          SIGNING_PGP_PASSWORD: ${{ secrets.SIGNING_PGP_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}

      - name: Prepare Docker build
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: assembleLib --no-daemon

      - name: DockerHub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: DockerHub publish
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
          context: .
          push: true
          tags: |
            sandpolis/desktop-client:latest
            sandpolis/desktop-client:${{ steps.get_version.outputs.tag }}

      - name: Update DockerHub Readme
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: sandpolis/desktop-client
