[package]
name = "sandpolis-core-instance"
version = "0.1.0"
edition = "2021"
build = "src/main/rust/build.rs"

[lib]
name = "core_instance"
path = "src/main/rust/lib.rs"

[dependencies]
prost = { version = "0.6", default-features = false, features = ["prost-derive"] }

[build-dependencies]
prost-build = { version = "0.9.0" }
