
[changelog]
commit_parsers = [
  { message = "^impr", group = "improved" },
  { message = "^changed", group = "changed" },
  { message = "^deprecated", group = "deprecated" },
  { message = "^fix", group = "fixed" },
  { message = "^security", group = "security" },
  { message = "^.*", skip = true },
]
