[package]
name = "sandpolis-user"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
totp-rs = { version = "5.6.0", optional = true, features = [
  "otpauth",
  "zeroize",
] }
argon2 = { version = "0.5.3", optional = true }
jsonwebtoken = { version = "9.3.0", optional = true }
regex = { workspace = true }
tracing = { workspace = true }
validator = { workspace = true }
sandpolis-instance = { path = "../sandpolis-instance" }

[features]
server = [
  "dep:totp-rs",
  "totp-rs?/gen_secret",
  "dep:argon2",
  "dep:jsonwebtoken",
]
client = ["dep:totp-rs", "totp-rs?/qr", "dep:argon2"]
