[package]
name = "sandpolis-group"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
rcgen = { version = "0.13.1", optional = true, features = [
  "crypto",
  "pem",
  "x509-parser",
] }
rustls-pki-types = { version = "1.10.1", optional = true }

[features]
server = ["dep:rcgen", "rustls-pki-types"]
