[package]
name = "sandpolis-bootagent"
version = "0.0.1"
edition = "2021"

[dependencies]
uefi = { version = "0.30.0", features = ["panic_handler"] }
smoltcp = { version = "0.11.0", default-features = false, features = ["log", "alloc", "proto-ipv4"] }
# ring = "0.17.8"
