[package]
name = "sandpolis-location"
version = "0.0.1"
edition = "2024"

[dependencies]
reqwest = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[features]
server = []
client = []
