[package]
description = "Virtual estate monitoring & management!"
edition = "2024"
license = "Unlicense"
name = "sandpolis-audit"
version = "0.0.1"

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
inventory = { workspace = true }
linux-audit-parser = "0.2.7"
native_db = { workspace = true }
native_model = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
sandpolis-instance = { path = "../sandpolis-instance", version = "0.0.1" }
sandpolis-macros = { path = "../sandpolis-macros", version = "0.0.1" }

[dev-dependencies]
tempfile = { workspace = true }
test-log = { version = "0.2.18", features = ["trace"] }
tokio = { workspace = true }

[features]
agent = ["sandpolis-instance/agent"]
client = ["sandpolis-instance/client"]
server = ["sandpolis-instance/server"]
