[package]
name = "sandpolis-desktop"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { workspace = true }
serde = { workspace = true }
anyhow = { workspace = true }
# TODO needs to be published
# scrap = { git = "https://github.com/rustdesk/rustdesk", optional = true, features = [
#   "linux-pkg-config",
# ] }
enigo = { version = "0.3.0", optional = true }
tracing = { workspace = true }

[features]
agent = ["dep:enigo"]
client = []
client-gui = ["client"]
client-tui = ["client"]
server = []
