use crate::database::{DatabaseManager, Resident, ResidentVec};
use crate::domain::DomainData;
use crate::realm::RealmName;
use anyhow::{Result, bail};
use native_db::ToKey;
use native_model::Model;
use sandpolis_macros::data;
use serde::{Deserialize, Serialize, de::DeserializeOwned};
use std::cmp::Ordering;
use std::fmt::{Display, Write};
use std::str::FromStr;
use strum::{EnumIter, IntoEnumIterator};
use tracing::trace;
use uuid::Uuid;

#[cfg(not(target_os = "android"))]
pub mod cli;
pub mod config;
pub mod database;
pub mod domain;
pub mod network;
pub mod notification;
pub mod realm;
pub mod service;

/// Re-exported so code generated by `sandpolis_macros::data` can invoke
/// `inventory::submit!` from crates that do not depend on `inventory` directly.
pub use inventory;

/// Format a UUID in the usual "lowercase hex encoded with hyphens" style.
#[inline]
fn format_uuid(src: u128) -> [u8; 36] {
    let src: [u8; 16] = src.to_le_bytes();
    let lut = *b"0123456789abcdef";

    let groups = [(0, 8), (9, 13), (14, 18), (19, 23), (24, 36)];
    let mut dst = [0; 36];

    let mut group_idx = 0;
    let mut i = 0;
    while group_idx < 5 {
        let (start, end) = groups[group_idx];
        let mut j = start;
        while j < end {
            let x = src[i];
            i += 1;

            dst[j] = lut[(x >> 4) as usize];
            dst[j + 1] = lut[(x & 0x0f) as usize];
            j += 2;
        }
        if group_idx < 4 {
            dst[end] = b'-';
        }
        group_idx += 1;
    }
    dst
}

/// Shared ID across the entire cluster. This never changes throughout the
/// cluster's lifetime.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct ClusterId(u128);

impl ClusterId {
    pub fn as_bytes(&self) -> [u8; 16] {
        self.0.to_be_bytes()
    }
}

// `serde_cbor` cannot encode `u128`, so represent the id as its raw little-endian
// bytes. This is format-agnostic (CBOR, JSON, etc.) and consistent across peers.
impl Serialize for ClusterId {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        self.0.to_le_bytes().serialize(serializer)
    }
}

impl<'de> Deserialize<'de> for ClusterId {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        Ok(ClusterId(u128::from_le_bytes(<[u8; 16]>::deserialize(
            deserializer,
        )?)))
    }
}

impl Display for ClusterId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(std::str::from_utf8(&format_uuid(self.0)).unwrap())
    }
}

impl Default for ClusterId {
    fn default() -> Self {
        Self(Uuid::now_v7().to_u128_le())
    }
}

impl FromStr for ClusterId {
    type Err = anyhow::Error;

    fn from_str(s: &str) -> Result<Self> {
        let uuid = Uuid::parse_str(s)?;
        Ok(ClusterId(uuid.to_u128_le()))
    }
}

#[cfg(test)]
mod test_cluster_id {
    use super::*;
    #[test]
    fn test_display() {
        assert_eq!(ClusterId::default().to_string().len(), 36);
    }
}

/// All instances are identified by a unique 128-bit string that's generated on
/// first start. This identifier is reused for all subsequent runs.
#[cfg_attr(feature = "client", derive(bevy::prelude::Component))]
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct InstanceId(u128);

// `serde_cbor` cannot encode `u128`, so represent the id as its raw little-endian
// bytes. This is format-agnostic (CBOR, JSON, etc.) and consistent across peers.
impl Serialize for InstanceId {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        self.0.to_le_bytes().serialize(serializer)
    }
}

impl<'de> Deserialize<'de> for InstanceId {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        Ok(InstanceId(u128::from_le_bytes(<[u8; 16]>::deserialize(
            deserializer,
        )?)))
    }
}

impl InstanceId {
    /// Generate a new instance ID for an instance of the given type.
    pub fn new(instance_type: InstanceType) -> Self {
        // A v7 uuid leads with its timestamp, so ids generated near each other
        // share a long prefix. `format_uuid` renders the low bytes first, which
        // reverses that: the random bytes come first and two ids differ from the
        // start. It also keeps the timestamp clear of the nibble below, which is
        // what makes `timestamp` recoverable.
        let mut uuid = Uuid::now_v7().as_u128();

        // Wipe out last nibble
        uuid &= 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0;

        uuid |= instance_type.mask() as u128;

        trace!(id = uuid, "Generated new instance ID");
        Self(uuid)
    }

    /// Generate a new server ID as a convenience.
    pub fn new_server() -> Self {
        Self::new(InstanceType::Server)
    }

    /// Check whether this UUID was generated with the given instance type.
    pub fn is_type(&self, instance_type: InstanceType) -> bool {
        self.0 & instance_type.mask() as u128 > 0
    }

    pub fn is_server(&self) -> bool {
        self.is_type(InstanceType::Server)
    }

    pub fn is_client(&self) -> bool {
        self.is_type(InstanceType::Client)
    }

    pub fn is_agent(&self) -> bool {
        self.is_type(InstanceType::Agent)
    }

    /// Whether an instance of this type can belong to a domain. Domains group
    /// the estate, not the servers running it.
    pub fn is_domain_member(&self) -> bool {
        self.is_agent() || self.is_client()
    }

    /// Return the instance type encoded in this UUID, or `None` if it names no
    /// instance (see [`Default`]).
    pub fn instance_type(&self) -> Option<InstanceType> {
        InstanceType::iter().find(|t| self.is_type(*t))
    }

    /// Return when this id was generated, in milliseconds since the unix epoch.
    ///
    /// This is the v7 uuid's own timestamp, so it's only as trustworthy as the
    /// clock of whatever instance generated the id. Zero for [`Default`], which
    /// was never generated at all.
    pub fn timestamp(&self) -> u64 {
        // v7 puts a 48-bit millisecond timestamp in the uuid's leading bytes,
        // which `new` leaves untouched.
        (self.0 >> 80) as u64
    }
}

/// The id that names no instance. Data models derive `Default`, so every
/// `InstanceId` field starts here and is overwritten with a real id by whatever
/// knows one. Nothing is ever generated by default, which would look like a real
/// instance nobody can reach.
impl Default for InstanceId {
    fn default() -> Self {
        Self(0)
    }
}

impl Display for InstanceId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(std::str::from_utf8(&format_uuid(self.0)).unwrap())
    }
}

impl FromStr for InstanceId {
    type Err = anyhow::Error;

    /// Inverse of [`Display`]: parse the uuid-formatted string back into the
    /// little-endian bytes used to construct it.
    fn from_str(s: &str) -> Result<Self> {
        let hex: String = s.chars().filter(|c| *c != '-').collect();
        if hex.len() != 32 {
            anyhow::bail!("invalid InstanceId: {s}");
        }
        let mut bytes = [0u8; 16];
        for (i, byte) in bytes.iter_mut().enumerate() {
            *byte = u8::from_str_radix(&hex[i * 2..i * 2 + 2], 16)?;
        }
        Ok(InstanceId(u128::from_le_bytes(bytes)))
    }
}

impl ToKey for InstanceId {
    fn to_key(&self) -> native_db::Key {
        native_db::Key::new(self.0.to_be_bytes().to_vec())
    }

    fn key_names() -> Vec<String> {
        vec!["InstanceId".to_string()]
    }
}

/// All possible instance types.
#[derive(
    Serialize, Deserialize, Clone, Copy, EnumIter, Debug, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
pub enum InstanceType {
    /// Runs continuously on hosts and responds to management requests from
    /// servers and clients.
    Agent,

    /// User interface for managing instances in the Sandpolis network.
    Client,

    /// Runs continously and coordinates interactions among instances in a
    /// Sandpolis network. All networks include at least one server
    /// instance.
    Server,
    // Probes are not technically instances, but they can connect to proper
    // agents/server instances and appear like standalone instances.
}

impl InstanceType {
    /// Each instance type has an identifier.
    pub const fn mask(&self) -> u8 {
        match self {
            InstanceType::Agent => 0b00000001,
            InstanceType::Client => 0b00000010,
            InstanceType::Server => 0b00000100,
        }
    }

    /// Each instance type has an associated color.
    pub const fn color(&self) -> colored::Color {
        match self {
            InstanceType::Agent => colored::Color::Cyan,
            InstanceType::Client => colored::Color::Green,
            InstanceType::Server => colored::Color::Magenta,
        }
    }
}

#[cfg(test)]
mod test_instance_id {
    use super::*;

    /// The generation timestamp survives the type nibble, for every type: the
    /// two used to overlap, and the id's own creation time was unrecoverable.
    #[test]
    fn test_timestamp() {
        for instance_type in InstanceType::iter() {
            let before = chrono::Utc::now().timestamp_millis() as u64;
            let id = InstanceId::new(instance_type);
            let after = chrono::Utc::now().timestamp_millis() as u64;

            assert!(
                (before..=after).contains(&id.timestamp()),
                "{instance_type:?} id {id} reported {}, expected {before}..={after}",
                id.timestamp()
            );
        }
    }

    /// The id that names no instance was never generated, so it has no
    /// creation time either.
    #[test]
    fn test_default_has_no_timestamp() {
        assert_eq!(InstanceId::default().timestamp(), 0);
    }

    /// Ids generated back to back have to be told apart at a glance, which is
    /// why the formatted id leads with the uuid's random bytes rather than its
    /// timestamp.
    #[test]
    fn test_display_differs_early() {
        let first = InstanceId::new(InstanceType::Agent).to_string();
        let second = InstanceId::new(InstanceType::Agent).to_string();

        let common = first
            .chars()
            .zip(second.chars())
            .take_while(|(a, b)| a == b)
            .count();
        assert!(
            common < 8,
            "ids share a {common} character prefix: {first} / {second}"
        );
    }

    #[test]
    fn test_new_single_types() {
        let agent_id = InstanceId::new(InstanceType::Agent);
        assert!(agent_id.is_agent());
        assert!(!agent_id.is_server());
        assert!(!agent_id.is_client());

        let server_id = InstanceId::new(InstanceType::Server);
        assert!(!server_id.is_agent());
        assert!(server_id.is_server());
        assert!(!server_id.is_client());

        let client_id = InstanceId::new(InstanceType::Client);
        assert!(!client_id.is_agent());
        assert!(!client_id.is_server());
        assert!(client_id.is_client());
    }

    #[test]
    fn test_domain_membership() {
        // Domains group the estate, not the servers running it.
        assert!(!InstanceId::new(InstanceType::Server).is_domain_member());

        assert!(InstanceId::new(InstanceType::Agent).is_domain_member());
        assert!(InstanceId::new(InstanceType::Client).is_domain_member());
    }

    /// The default id names no instance at all, so it can never be mistaken for
    /// one that's merely unreachable.
    #[test]
    fn test_default_is_typeless() {
        let id = InstanceId::default();
        assert!(!id.is_agent());
        assert!(!id.is_client());
        assert!(!id.is_server());
        assert_eq!(id.instance_type(), None);
        assert_eq!(id, InstanceId::default());
    }

    #[test]
    fn test_instance_type_method() {
        assert_eq!(
            InstanceId::new(InstanceType::Agent).instance_type(),
            Some(InstanceType::Agent)
        );
        assert_eq!(
            InstanceId::new(InstanceType::Client).instance_type(),
            Some(InstanceType::Client)
        );
        assert_eq!(
            InstanceId::new(InstanceType::Server).instance_type(),
            Some(InstanceType::Server)
        );
    }

    #[test]
    fn test_display_format() {
        let id = InstanceId(0x123456789ABCDEF0FEDCBA0987654321);
        let display_str = id.to_string();

        // Should be 36 characters (32 hex + 4 hyphens)
        assert_eq!(display_str.len(), 36);

        // Should contain hyphens in the right positions
        assert_eq!(display_str.chars().nth(8), Some('-'));
        assert_eq!(display_str.chars().nth(13), Some('-'));
        assert_eq!(display_str.chars().nth(18), Some('-'));
        assert_eq!(display_str.chars().nth(23), Some('-'));

        // Should be all lowercase hex
        assert!(
            display_str
                .chars()
                .all(|c| c.is_ascii_hexdigit() || c == '-')
        );
        assert!(display_str.chars().all(|c| !c.is_ascii_uppercase()));
    }

    #[test]
    fn test_type_masks() {
        // Test that the type masks work correctly
        let agent_id = InstanceId::new(InstanceType::Agent);
        let server_id = InstanceId::new(InstanceType::Server);
        let client_id = InstanceId::new(InstanceType::Client);

        // Check that the masks are applied correctly
        assert_eq!(
            agent_id.0 & InstanceType::Agent.mask() as u128,
            InstanceType::Agent.mask() as u128
        );
        assert_eq!(
            server_id.0 & InstanceType::Server.mask() as u128,
            InstanceType::Server.mask() as u128
        );
        assert_eq!(
            client_id.0 & InstanceType::Client.mask() as u128,
            InstanceType::Client.mask() as u128
        );

        // Check that other masks are not set
        assert_eq!(agent_id.0 & InstanceType::Server.mask() as u128, 0);
        assert_eq!(agent_id.0 & InstanceType::Client.mask() as u128, 0);
    }

    #[test]
    fn test_mask_bitwise_operations() {
        // Test that the masks are properly distinct
        assert_ne!(InstanceType::Agent.mask(), InstanceType::Server.mask());
        assert_ne!(InstanceType::Agent.mask(), InstanceType::Client.mask());
        assert_ne!(InstanceType::Server.mask(), InstanceType::Client.mask());

        // Test that combining masks works
        let combined = InstanceType::Agent.mask() | InstanceType::Server.mask();
        assert_ne!(combined, InstanceType::Agent.mask());
        assert_ne!(combined, InstanceType::Server.mask());
        assert_eq!(
            combined & InstanceType::Agent.mask(),
            InstanceType::Agent.mask()
        );
        assert_eq!(
            combined & InstanceType::Server.mask(),
            InstanceType::Server.mask()
        );
    }
}

/// Names a _layer_: the GUI face a subsystem presents, which the client's layer
/// picker chooses between and which notifications and services are attributed
/// to. A subsystem provides at most one, so the layer's name is the subsystem's
/// name (e.g. `"Shell"`, `"Inventory"`).
///
/// Layers are registered at runtime using the `inventory` crate.
#[cfg_attr(feature = "client", derive(bevy::prelude::Resource))]
#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize)]
pub struct LayerName(pub String);

impl LayerName {
    /// Create a new layer with the given name.
    pub const fn new(name: String) -> Self {
        Self(name)
    }

    /// Get the layer name.
    pub fn name(&self) -> &str {
        &self.0
    }

    /// Iterate over all registered layers.
    pub fn registered() -> impl Iterator<Item = &'static LayerName> {
        inventory::iter::<LayerName>()
    }
}

impl std::fmt::Display for LayerName {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.0)
    }
}

impl std::ops::Deref for LayerName {
    type Target = str;

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl From<&str> for LayerName {
    fn from(s: &str) -> Self {
        Self(s.to_string())
    }
}

impl From<String> for LayerName {
    fn from(s: String) -> Self {
        Self(s)
    }
}

impl PartialEq<str> for LayerName {
    fn eq(&self, other: &str) -> bool {
        self.0 == other
    }
}

impl PartialEq<&str> for LayerName {
    fn eq(&self, other: &&str) -> bool {
        self.0 == *other
    }
}

// Register LayerName with inventory for runtime collection
inventory::collect!(LayerName);

#[data]
#[derive(Default)]
pub struct InstanceManagerData {
    pub cluster_id: ClusterId,
    /// The instance this row describes — also this row's owning scope, so a
    /// server can own exactly the identity rows of the instances attached to it.
    #[secondary_key]
    pub _instance_id: InstanceId,
    pub os_info: os_info::Info,
}

// Scoped by the instance the record describes, so a local stratum server can
// subscribe to just the instances connected to it. Without this the set of known
// instances never replicates at all and every peer looks empty.
inventory::submit! {
    crate::database::sync::SyncRegistration(
        |r| r.register_scoped::<InstanceManagerData>(|d| d._instance_id))
}

/// The sync `model_id` for [`InstanceManagerData`], used by clients to subscribe to
/// the set of known instances.
pub fn instance_manager_model_id() -> u32 {
    use native_model::Model;
    <InstanceManagerData as Model>::native_model_id()
}

#[derive(Clone)]
#[cfg_attr(feature = "client", derive(bevy::prelude::Resource))]
pub struct InstanceManager {
    /// Every domain in the estate. Assigned by the global stratum server and
    /// replicated from there, so this is a read-only view everywhere else.
    domains: ResidentVec<DomainData>,
    /// Every instance in the estate, replicated in. The client's world view is
    /// drawn from this, so it covers instances this one never talks to.
    instances: ResidentVec<InstanceManagerData>,
    /// The default realm, so callers that need one (the service runner, say)
    /// don't have to be handed the whole [`DatabaseManager`].
    realm: crate::database::RealmDatabase,
    pub instance_id: InstanceId,
    pub cluster_id: ClusterId,
}

impl InstanceManager {
    /// `instance_type` is what this process was started as, which is what its
    /// identity says about it forever after.
    pub async fn new(database: DatabaseManager, instance_type: InstanceType) -> Result<Self> {
        let realm = database.realm(RealmName::default())?;

        // The identity row is generated on first start and reused forever after.
        // It is seeded as instance-local bookkeeping rather than through the
        // scope gate: the row's own scope is this instance's id, which isn't
        // known until the row exists.
        {
            let r = realm.r_transaction()?;
            let existing = r
                .scan()
                .primary::<InstanceManagerData>()?
                .all()?
                .next()
                .transpose()?;
            drop(r);

            if existing.is_none() {
                let rw = realm.local_write()?;
                rw.insert(InstanceManagerData {
                    _instance_id: InstanceId::new(instance_type),
                    ..Default::default()
                })?;
                rw.commit()?;
            }
        }

        let data: Resident<InstanceManagerData> = realm.resident(())?;

        let instance_id = data.read()._instance_id;

        // A data directory belongs to the instance that created it. Running a
        // different instance against it would mean two instances sharing one
        // identity, which is exactly what this identity exists to prevent.
        if !instance_id.is_type(instance_type) {
            bail!(
                "This data directory belongs to a {:?} instance ({instance_id}), \
                 so a {instance_type:?} cannot run against it. Give each instance \
                 its own --data directory.",
                instance_id.instance_type()
            );
        }

        // With scoped authority, the self scope becomes writable from here on.
        if let Some(table) = database.authority().scope_table() {
            table.set_self(instance_id);
        }

        // Every subsystem raises notifications through a process-wide handle, so it
        // is installed here — the first point that knows both the database and
        // this instance's id. Idempotent, since startup builds an `InstanceManager`
        // more than once.
        crate::notification::install(&realm, instance_id);

        Ok(Self {
            instance_id,
            cluster_id: { data.read().cluster_id },
            domains: realm.resident_vec(())?,
            instances: realm.resident_vec(())?,
            realm,
        })
    }

    /// What this process is: agent, client, or server.
    pub fn instance_type(&self) -> InstanceType {
        self.instance_id
            .instance_type()
            .expect("the local instance id always names a type")
    }

    /// The domain the given instance belongs to, if any.
    ///
    /// Servers are never members, so the rule is applied here too: a server that
    /// somehow appears in a domain's member list still resolves to nothing.
    pub fn domain_of(&self, id: InstanceId) -> Option<String> {
        if !id.is_domain_member() {
            return None;
        }

        self.domains.iter().find_map(|domain| {
            let domain = domain.read();
            domain
                .members
                .contains(&id)
                .then(|| domain.name.trim().to_string())
                .filter(|name| !name.is_empty())
        })
    }

    /// Every domain in the estate.
    pub fn domains(&self) -> &ResidentVec<DomainData> {
        &self.domains
    }

    /// Every instance the estate knows about, this one included.
    ///
    /// A client draws a node per entry, which is how an agent it holds no
    /// connection to shows up at all.
    pub fn instances(&self) -> &ResidentVec<InstanceManagerData> {
        &self.instances
    }

    /// This instance's default realm.
    pub fn realm(&self) -> &crate::database::RealmDatabase {
        &self.realm
    }
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct LayerVersion {
    pub major: u32,
    pub minor: u32,
    pub patch: u32,
    pub description: Option<String>,
    // pub rev: Option<String>,
    // pub build_time: Option<String>,
}

impl TryFrom<String> for LayerVersion {
    type Error = anyhow::Error;

    /// Parse `major.minor.patch` with an optional `-description` suffix, which
    /// is the shape cargo's `CARGO_PKG_VERSION` takes.
    fn try_from(value: String) -> Result<Self, Self::Error> {
        let (numbers, description) = match value.split_once('-') {
            Some((numbers, description)) => (numbers, Some(description.to_string())),
            None => (value.as_str(), None),
        };

        let mut parts = numbers.split('.');
        let mut number = |field: &str| -> Result<u32, Self::Error> {
            parts
                .next()
                .ok_or_else(|| anyhow::anyhow!("missing {field} version in: {value}"))?
                .parse()
                .map_err(|_| anyhow::anyhow!("invalid {field} version in: {value}"))
        };

        let major = number("major")?;
        let minor = number("minor")?;
        let patch = number("patch")?;

        if parts.next().is_some() {
            anyhow::bail!("trailing version component in: {value}");
        }

        Ok(Self {
            major,
            minor,
            patch,
            description,
        })
    }
}

impl PartialOrd for LayerVersion {
    fn partial_cmp(&self, other: &Self) -> Option<Ordering> {
        Some(self.cmp(other))
    }
}

impl Ord for LayerVersion {
    fn cmp(&self, other: &Self) -> Ordering {
        if self.major > other.major {
            Ordering::Greater
        } else if self.major < other.major {
            Ordering::Less
        } else if self.minor > other.minor {
            Ordering::Greater
        } else if self.minor < other.minor {
            Ordering::Less
        } else if self.patch > other.patch {
            Ordering::Greater
        } else if self.patch < other.patch {
            Ordering::Less
        } else {
            Ordering::Equal
        }
    }
}

#[cfg(test)]
mod test_layer_version {
    use super::*;

    #[test]
    fn test_parse() {
        let version = LayerVersion::try_from("1.2.3".to_string()).unwrap();
        assert_eq!(version.major, 1);
        assert_eq!(version.minor, 2);
        assert_eq!(version.patch, 3);
        assert_eq!(version.description, None);
    }

    /// This crate's own version has to parse, since that's where these come
    /// from.
    #[test]
    fn test_parse_own_version() {
        LayerVersion::try_from(env!("CARGO_PKG_VERSION").to_string()).unwrap();
    }

    #[test]
    fn test_parse_with_description() {
        let version = LayerVersion::try_from("0.1.0-alpha.1".to_string()).unwrap();
        assert_eq!(version.major, 0);
        assert_eq!(version.minor, 1);
        assert_eq!(version.patch, 0);
        assert_eq!(version.description.as_deref(), Some("alpha.1"));
    }

    #[test]
    fn test_parse_rejects_malformed() {
        for value in ["", "1", "1.2", "1.2.3.4", "1.2.x", "v1.2.3", "-1.2.3"] {
            assert!(
                LayerVersion::try_from(value.to_string()).is_err(),
                "expected {value} to be rejected"
            );
        }
    }

    /// Ordering ignores the description, so a prerelease and its release
    /// compare equal.
    #[test]
    fn test_ordering() {
        let older = LayerVersion::try_from("1.2.3".to_string()).unwrap();
        let newer = LayerVersion::try_from("1.3.0".to_string()).unwrap();
        assert!(newer > older);
        assert!(older < LayerVersion::try_from("2.0.0".to_string()).unwrap());
        assert_eq!(
            older.cmp(&LayerVersion::try_from("1.2.3-alpha".to_string()).unwrap()),
            Ordering::Equal
        );
    }
}
