use crate::database::{DatabaseLayer, Resident};
use crate::realm::RealmName;
use anyhow::{Result, bail};
use native_db::ToKey;
use native_model::Model;
use sandpolis_macros::data;
use serde::{Deserialize, Serialize, de::DeserializeOwned};
use std::cmp::Ordering;
use std::fmt::{Display, Write};
use std::str::FromStr;
use strum::{EnumIter, IntoEnumIterator};
use tracing::{info, trace, warn};
use uuid::Uuid;

#[cfg(not(target_os = "android"))]
pub mod cli;
pub mod config;
pub mod database;
pub mod network;
pub mod realm;
pub mod service;

/// Re-exported so code generated by `sandpolis_macros::data` can invoke
/// `inventory::submit!` from crates that do not depend on `inventory` directly.
pub use inventory;

/// Format a UUID in the usual "lowercase hex encoded with hyphens" style.
#[inline]
fn format_uuid(src: u128) -> [u8; 36] {
    let src: [u8; 16] = src.to_le_bytes();
    let lut = *b"0123456789abcdef";

    let groups = [(0, 8), (9, 13), (14, 18), (19, 23), (24, 36)];
    let mut dst = [0; 36];

    let mut group_idx = 0;
    let mut i = 0;
    while group_idx < 5 {
        let (start, end) = groups[group_idx];
        let mut j = start;
        while j < end {
            let x = src[i];
            i += 1;

            dst[j] = lut[(x >> 4) as usize];
            dst[j + 1] = lut[(x & 0x0f) as usize];
            j += 2;
        }
        if group_idx < 4 {
            dst[end] = b'-';
        }
        group_idx += 1;
    }
    dst
}

/// Shared ID across the entire cluster. This never changes throughout the
/// cluster's lifetime.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct ClusterId(u128);

impl ClusterId {
    pub fn as_bytes(&self) -> [u8; 16] {
        self.0.to_be_bytes()
    }
}

// `serde_cbor` cannot encode `u128`, so represent the id as its raw little-endian
// bytes. This is format-agnostic (CBOR, JSON, etc.) and consistent across peers.
impl Serialize for ClusterId {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        self.0.to_le_bytes().serialize(serializer)
    }
}

impl<'de> Deserialize<'de> for ClusterId {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        Ok(ClusterId(u128::from_le_bytes(<[u8; 16]>::deserialize(
            deserializer,
        )?)))
    }
}

impl Display for ClusterId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(std::str::from_utf8(&format_uuid(self.0)).unwrap())
    }
}

impl Default for ClusterId {
    fn default() -> Self {
        Self(Uuid::now_v7().to_u128_le())
    }
}

impl FromStr for ClusterId {
    type Err = anyhow::Error;

    fn from_str(s: &str) -> Result<Self> {
        let uuid = Uuid::parse_str(s)?;
        Ok(ClusterId(uuid.to_u128_le()))
    }
}

#[cfg(test)]
mod test_cluster_id {
    use super::*;
    #[test]
    fn test_display() {
        assert_eq!(ClusterId::default().to_string().len(), 36);
    }
}

/// All instances are identified by a unique 128-bit string that's generated on
/// first start. This identifier is reused for all subsequent runs.
#[cfg_attr(feature = "client", derive(bevy::prelude::Component))]
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct InstanceId(u128);

// `serde_cbor` cannot encode `u128`, so represent the id as its raw little-endian
// bytes. This is format-agnostic (CBOR, JSON, etc.) and consistent across peers.
impl Serialize for InstanceId {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        self.0.to_le_bytes().serialize(serializer)
    }
}

impl<'de> Deserialize<'de> for InstanceId {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        Ok(InstanceId(u128::from_le_bytes(<[u8; 16]>::deserialize(
            deserializer,
        )?)))
    }
}

impl InstanceId {
    /// Generate a new instance ID for an instance of the given type(s).
    pub fn new(instance_types: &[InstanceType]) -> Self {
        if instance_types.is_empty() {
            panic!("No instance type given");
        }

        // Reverse the UUID to make visual comparison easier (dispersing the prefixes
        // makes it easier to tell two UUIDs apart).
        let mut uuid = Uuid::now_v7().to_u128_le();

        // Wipe out last nibble
        uuid &= 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0;

        for instance_type in instance_types {
            uuid |= instance_type.mask() as u128;
        }

        trace!(id = uuid, "Generated new instance ID");
        Self(uuid)
    }

    /// Generate a new server-only ID as a convenience.
    pub fn new_server() -> Self {
        Self::new(&[InstanceType::Server])
    }

    /// Check whether this UUID was generated with the given instance type.
    pub fn is_type(&self, instance_type: InstanceType) -> bool {
        self.0 & instance_type.mask() as u128 > 0
    }

    pub fn is_server(&self) -> bool {
        self.is_type(InstanceType::Server)
    }

    pub fn is_client(&self) -> bool {
        self.is_type(InstanceType::Client)
    }

    pub fn is_agent(&self) -> bool {
        self.is_type(InstanceType::Agent)
    }

    /// Return the instance types encoded in this UUID.
    pub fn types(&self) -> Vec<InstanceType> {
        InstanceType::iter().filter(|t| self.is_type(*t)).collect()
    }

    /// Return the timestamp when the UUID was generated.
    pub fn timestamp(&self) -> u64 {
        todo!()
    }
}

impl Default for InstanceId {
    fn default() -> Self {
        Self::new(&[
            #[cfg(feature = "server")]
            InstanceType::Server,
            #[cfg(feature = "client")]
            InstanceType::Client,
            #[cfg(feature = "agent")]
            InstanceType::Agent,
        ])
    }
}

impl Display for InstanceId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(std::str::from_utf8(&format_uuid(self.0)).unwrap())
    }
}

impl FromStr for InstanceId {
    type Err = anyhow::Error;

    /// Inverse of [`Display`]: parse the uuid-formatted string back into the
    /// little-endian bytes used to construct it.
    fn from_str(s: &str) -> Result<Self> {
        let hex: String = s.chars().filter(|c| *c != '-').collect();
        if hex.len() != 32 {
            anyhow::bail!("invalid InstanceId: {s}");
        }
        let mut bytes = [0u8; 16];
        for (i, byte) in bytes.iter_mut().enumerate() {
            *byte = u8::from_str_radix(&hex[i * 2..i * 2 + 2], 16)?;
        }
        Ok(InstanceId(u128::from_le_bytes(bytes)))
    }
}

impl ToKey for InstanceId {
    fn to_key(&self) -> native_db::Key {
        native_db::Key::new(self.0.to_be_bytes().to_vec())
    }

    fn key_names() -> Vec<String> {
        vec!["InstanceId".to_string()]
    }
}

/// All possible instance types.
#[derive(
    Serialize, Deserialize, Clone, Copy, EnumIter, Debug, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
pub enum InstanceType {
    /// Runs continuously on hosts and responds to management requests from
    /// servers and clients.
    Agent,

    /// User interface for managing instances in the Sandpolis network.
    Client,

    /// Runs continously and coordinates interactions among instances in a
    /// Sandpolis network. All networks include at least one server
    /// instance.
    Server,
    // Probes are not technically instances, but they can connect to proper
    // agents/server instances and appear like standalone instances.
}

impl InstanceType {
    /// Each instance type has an identifier.
    pub const fn mask(&self) -> u8 {
        match self {
            InstanceType::Agent => 0b00000001,
            InstanceType::Client => 0b00000010,
            InstanceType::Server => 0b00000100,
        }
    }

    /// Each instance type has an associated color.
    pub const fn color(&self) -> colored::Color {
        match self {
            InstanceType::Agent => colored::Color::Cyan,
            InstanceType::Client => colored::Color::Green,
            InstanceType::Server => colored::Color::Magenta,
        }
    }
}

#[cfg(test)]
mod test_instance_id {
    use super::*;

    #[test]
    fn test_new_single_types() {
        let agent_id = InstanceId::new(&[InstanceType::Agent]);
        assert!(agent_id.is_agent());
        assert!(!agent_id.is_server());
        assert!(!agent_id.is_client());

        let server_id = InstanceId::new(&[InstanceType::Server]);
        assert!(!server_id.is_agent());
        assert!(server_id.is_server());
        assert!(!server_id.is_client());

        let client_id = InstanceId::new(&[InstanceType::Client]);
        assert!(!client_id.is_agent());
        assert!(!client_id.is_server());
        assert!(client_id.is_client());
    }

    #[test]
    fn test_new_multiple_types() {
        let multi_id = InstanceId::new(&[InstanceType::Agent, InstanceType::Server]);
        assert!(multi_id.is_agent());
        assert!(multi_id.is_server());
        assert!(!multi_id.is_client());

        let all_types_id = InstanceId::new(&[
            InstanceType::Agent,
            InstanceType::Server,
            InstanceType::Client,
        ]);
        assert!(all_types_id.is_agent());
        assert!(all_types_id.is_server());
        assert!(all_types_id.is_client());
    }

    #[test]
    fn test_new_server_convenience() {
        let server_id = InstanceId::new_server();
        assert!(server_id.is_server());
        assert!(!server_id.is_agent());
        assert!(!server_id.is_client());
    }

    #[test]
    fn test_types_method() {
        let agent_id = InstanceId::new(&[InstanceType::Agent]);
        let types = agent_id.types();
        assert_eq!(types.len(), 1);
        assert!(types.contains(&InstanceType::Agent));

        let multi_id = InstanceId::new(&[InstanceType::Agent, InstanceType::Server]);
        let types = multi_id.types();
        assert_eq!(types.len(), 2);
        assert!(types.contains(&InstanceType::Agent));
        assert!(types.contains(&InstanceType::Server));
        assert!(!types.contains(&InstanceType::Client));
    }

    #[test]
    fn test_display_format() {
        let id = InstanceId(0x123456789ABCDEF0FEDCBA0987654321);
        let display_str = id.to_string();

        // Should be 36 characters (32 hex + 4 hyphens)
        assert_eq!(display_str.len(), 36);

        // Should contain hyphens in the right positions
        assert_eq!(display_str.chars().nth(8), Some('-'));
        assert_eq!(display_str.chars().nth(13), Some('-'));
        assert_eq!(display_str.chars().nth(18), Some('-'));
        assert_eq!(display_str.chars().nth(23), Some('-'));

        // Should be all lowercase hex
        assert!(
            display_str
                .chars()
                .all(|c| c.is_ascii_hexdigit() || c == '-')
        );
        assert!(display_str.chars().all(|c| !c.is_ascii_uppercase()));
    }

    #[test]
    fn test_type_masks() {
        // Test that the type masks work correctly
        let agent_id = InstanceId::new(&[InstanceType::Agent]);
        let server_id = InstanceId::new(&[InstanceType::Server]);
        let client_id = InstanceId::new(&[InstanceType::Client]);

        // Check that the masks are applied correctly
        assert_eq!(
            agent_id.0 & InstanceType::Agent.mask() as u128,
            InstanceType::Agent.mask() as u128
        );
        assert_eq!(
            server_id.0 & InstanceType::Server.mask() as u128,
            InstanceType::Server.mask() as u128
        );
        assert_eq!(
            client_id.0 & InstanceType::Client.mask() as u128,
            InstanceType::Client.mask() as u128
        );

        // Check that other masks are not set
        assert_eq!(agent_id.0 & InstanceType::Server.mask() as u128, 0);
        assert_eq!(agent_id.0 & InstanceType::Client.mask() as u128, 0);
    }

    #[test]
    fn test_multiple_type_masks() {
        let multi_id = InstanceId::new(&[InstanceType::Agent, InstanceType::Server]);

        // Should have both Agent and Server bits set
        assert_eq!(
            multi_id.0 & InstanceType::Agent.mask() as u128,
            InstanceType::Agent.mask() as u128
        );
        assert_eq!(
            multi_id.0 & InstanceType::Server.mask() as u128,
            InstanceType::Server.mask() as u128
        );

        // Should not have Client bit set
        assert_eq!(multi_id.0 & InstanceType::Client.mask() as u128, 0);
    }

    #[test]
    fn test_mask_bitwise_operations() {
        // Test that the masks are properly distinct
        assert_ne!(InstanceType::Agent.mask(), InstanceType::Server.mask());
        assert_ne!(InstanceType::Agent.mask(), InstanceType::Client.mask());
        assert_ne!(InstanceType::Server.mask(), InstanceType::Client.mask());

        // Test that combining masks works
        let combined = InstanceType::Agent.mask() | InstanceType::Server.mask();
        assert_ne!(combined, InstanceType::Agent.mask());
        assert_ne!(combined, InstanceType::Server.mask());
        assert_eq!(
            combined & InstanceType::Agent.mask(),
            InstanceType::Agent.mask()
        );
        assert_eq!(
            combined & InstanceType::Server.mask(),
            InstanceType::Server.mask()
        );
    }

    #[test]
    #[should_panic(expected = "No instance type given")]
    fn test_new_empty_types_panics() {
        InstanceId::new(&[]);
    }
}

/// A layer represents a functional area of Sandpolis (e.g., filesystem, shell, network).
/// Layers are registered at runtime using the `inventory` crate.
#[cfg_attr(feature = "client", derive(bevy::prelude::Resource))]
#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize)]
pub struct LayerName(pub String);

impl LayerName {
    /// Create a new layer with the given name.
    pub const fn new(name: String) -> Self {
        Self(name)
    }

    /// Get the layer name.
    pub fn name(&self) -> &str {
        &self.0
    }

    /// Iterate over all registered layers.
    pub fn registered() -> impl Iterator<Item = &'static LayerName> {
        inventory::iter::<LayerName>()
    }
}

impl std::fmt::Display for LayerName {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.0)
    }
}

impl std::ops::Deref for LayerName {
    type Target = str;

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl From<&str> for LayerName {
    fn from(s: &str) -> Self {
        Self(s.to_string())
    }
}

impl From<String> for LayerName {
    fn from(s: String) -> Self {
        Self(s)
    }
}

impl PartialEq<str> for LayerName {
    fn eq(&self, other: &str) -> bool {
        self.0 == other
    }
}

impl PartialEq<&str> for LayerName {
    fn eq(&self, other: &&str) -> bool {
        self.0 == *other
    }
}

// Register Layer with inventory for runtime collection
inventory::collect!(LayerName);

#[data]
#[derive(Default)]
pub struct InstanceLayerData {
    pub cluster_id: ClusterId,
    /// The instance this row describes — also this row's owning scope, so a
    /// server can own exactly the identity rows of the instances attached to it.
    #[secondary_key]
    pub _instance_id: InstanceId,
    pub os_info: os_info::Info,
    /// The domain this instance belongs to.
    ///
    /// Configured via `instance.domain` on the global stratum server, which is
    /// the only instance with a config file. Everyone else learns it from the
    /// server they connect to and persists it here, so it survives restarts even
    /// while the server is unreachable. Empty until that first connection.
    pub domain: String,
}

// Scoped by the instance the record describes, so a local stratum server can
// subscribe to just the instances connected to it. Without this the set of known
// instances never replicates at all and every peer looks empty.
inventory::submit! {
    crate::database::sync::SyncRegistration(
        |r| r.register_scoped::<InstanceLayerData>(|d| d._instance_id))
}

/// The sync `model_id` for [`InstanceLayerData`], used by clients to subscribe to
/// the set of known instances.
pub fn instance_layer_model_id() -> u32 {
    use native_model::Model;
    <InstanceLayerData as Model>::native_model_id()
}

#[derive(Clone)]
#[cfg_attr(feature = "client", derive(bevy::prelude::Resource))]
pub struct InstanceLayer {
    data: Resident<InstanceLayerData>,
    /// The default realm, so callers that need one (the service runner, say)
    /// don't have to be handed the whole [`DatabaseLayer`].
    realm: crate::database::RealmDatabase,
    pub instance_id: InstanceId,
    pub cluster_id: ClusterId,
}

impl InstanceLayer {
    /// `authoritative` is true only on the global stratum server, which owns the
    /// config file and therefore the domain. Everywhere else the domain is
    /// learned from the server on first connect (see [`set_domain`](Self::set_domain)).
    pub async fn new(
        config: &crate::config::InstanceConfig,
        database: DatabaseLayer,
        authoritative: bool,
    ) -> Result<Self> {
        let configured = config
            .domain
            .as_deref()
            .map(str::trim)
            .filter(|domain| !domain.is_empty());

        // The global stratum server is the origin of truth for the domain, so it
        // has to be told; nobody else can supply it.
        if authoritative && configured.is_none() {
            bail!("instance.domain must be configured in the global stratum server's config");
        }

        let realm = database.realm(RealmName::default())?;

        // The identity row is generated on first start and reused forever after.
        // It is seeded as instance-local bookkeeping rather than through the
        // scope gate: the row's own scope is this instance's id, which isn't
        // known until the row exists.
        {
            let r = realm.r_transaction()?;
            let existing = r
                .scan()
                .primary::<InstanceLayerData>()?
                .all()?
                .next()
                .transpose()?;
            drop(r);

            if existing.is_none() {
                let rw = realm.local_write()?;
                rw.insert(InstanceLayerData::default())?;
                rw.commit()?;
            }
        }

        let data: Resident<InstanceLayerData> = realm.resident(())?;

        // Persist the configured domain if it changed since the last start. A
        // non-authoritative instance keeps whatever it learned previously until
        // a server tells it otherwise.
        if let Some(domain) = configured {
            data.update_local(|d| {
                d.domain = domain.to_string();
                Ok(())
            })?;
        }

        let instance_id = data.read()._instance_id;

        // With scoped authority, the self scope becomes writable from here on.
        if let Some(table) = database.authority().scope_table() {
            table.set_self(instance_id);
        }

        Ok(Self {
            instance_id,
            cluster_id: { data.read().cluster_id },
            realm,
            data,
        })
    }

    /// The domain this instance belongs to, or empty if it hasn't learned one
    /// yet.
    pub fn domain(&self) -> String {
        self.data.read().domain.clone()
    }

    /// Record the domain reported by a server we just connected to.
    ///
    /// A no-op once a domain is known: the first server to answer sets it, and a
    /// later disagreement is logged rather than silently applied.
    pub fn set_domain(&self, domain: &str) -> Result<()> {
        let domain = domain.trim();
        if domain.is_empty() {
            return Ok(());
        }

        let current = self.domain();
        if current == domain {
            return Ok(());
        }
        if !current.is_empty() {
            warn!(
                current = %current,
                reported = %domain,
                "Server reported a different domain; keeping the one we have"
            );
            return Ok(());
        }

        info!(domain = %domain, "Learned domain from server");
        self.data.update_local(|d| {
            d.domain = domain.to_string();
            Ok(())
        })
    }

    /// This instance's default realm.
    pub fn realm(&self) -> &crate::database::RealmDatabase {
        &self.realm
    }
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct LayerVersion {
    pub major: u32,
    pub minor: u32,
    pub patch: u32,
    pub description: Option<String>,
    // pub rev: Option<String>,
    // pub build_time: Option<String>,
}

impl TryFrom<String> for LayerVersion {
    type Error = anyhow::Error;

    fn try_from(_value: String) -> Result<Self, Self::Error> {
        todo!()
    }
}

impl PartialOrd for LayerVersion {
    fn partial_cmp(&self, other: &Self) -> Option<Ordering> {
        Some(self.cmp(other))
    }
}

impl Ord for LayerVersion {
    fn cmp(&self, other: &Self) -> Ordering {
        if self.major > other.major {
            Ordering::Greater
        } else if self.major < other.major {
            Ordering::Less
        } else if self.minor > other.minor {
            Ordering::Greater
        } else if self.minor < other.minor {
            Ordering::Less
        } else if self.patch > other.patch {
            Ordering::Greater
        } else if self.patch < other.patch {
            Ordering::Less
        } else {
            Ordering::Equal
        }
    }
}

