use crate::database::{DatabaseManager, Resident, ResidentVec};
use crate::domain::DomainData;
use crate::realm::RealmName;
use anyhow::{Result, bail};
use native_db::ToKey;
use native_model::Model;
use sandpolis_macros::data;
use serde::{Deserialize, Serialize};
use std::cmp::Ordering;
use std::fmt::{Display, Write};
use std::str::FromStr;
use strum::{EnumIter, IntoEnumIterator};
use uuid::Uuid;

#[cfg(not(target_os = "android"))]
pub mod cli;
pub mod config;
pub mod database;
pub mod domain;
pub mod id;
pub mod network;
pub mod notification;
pub mod realm;
pub mod service;

/// Re-exported so code generated by `sandpolis_macros::data` can invoke
/// `inventory::submit!` from crates that do not depend on `inventory` directly.
pub use inventory;

/// Re-exported for code generated by [`typed_id!`].
#[doc(hidden)]
pub use {anyhow, native_db, serde};

pub use id::{AgentId, ClientId, InstanceId, ServerId};

/// Format a UUID in the usual "lowercase hex encoded with hyphens" style.
#[inline]
fn format_uuid(src: u128) -> [u8; 36] {
    let src: [u8; 16] = src.to_le_bytes();
    let lut = *b"0123456789abcdef";

    let groups = [(0, 8), (9, 13), (14, 18), (19, 23), (24, 36)];
    let mut dst = [0; 36];

    let mut group_idx = 0;
    let mut i = 0;
    while group_idx < 5 {
        let (start, end) = groups[group_idx];
        let mut j = start;
        while j < end {
            let x = src[i];
            i += 1;

            dst[j] = lut[(x >> 4) as usize];
            dst[j + 1] = lut[(x & 0x0f) as usize];
            j += 2;
        }
        if group_idx < 4 {
            dst[end] = b'-';
        }
        group_idx += 1;
    }
    dst
}

/// Shared ID across the entire cluster. This never changes throughout the
/// cluster's lifetime.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct ClusterId(u128);

impl ClusterId {
    pub fn as_bytes(&self) -> [u8; 16] {
        self.0.to_be_bytes()
    }
}

// `serde_cbor` cannot encode `u128`, so represent the id as its raw little-endian
// bytes. This is format-agnostic (CBOR, JSON, etc.) and consistent across peers.
impl Serialize for ClusterId {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        self.0.to_le_bytes().serialize(serializer)
    }
}

impl<'de> Deserialize<'de> for ClusterId {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        Ok(ClusterId(u128::from_le_bytes(<[u8; 16]>::deserialize(
            deserializer,
        )?)))
    }
}

impl Display for ClusterId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(std::str::from_utf8(&format_uuid(self.0)).unwrap())
    }
}

impl Default for ClusterId {
    fn default() -> Self {
        Self(Uuid::now_v7().to_u128_le())
    }
}

impl FromStr for ClusterId {
    type Err = anyhow::Error;

    fn from_str(s: &str) -> Result<Self> {
        let uuid = Uuid::parse_str(s)?;
        Ok(ClusterId(uuid.to_u128_le()))
    }
}

#[cfg(test)]
mod test_cluster_id {
    use super::*;
    #[test]
    fn test_display() {
        assert_eq!(ClusterId::default().to_string().len(), 36);
    }
}

/// All possible instance types.
#[derive(
    Serialize, Deserialize, Clone, Copy, EnumIter, Debug, PartialEq, Eq, PartialOrd, Ord, Hash,
)]
pub enum InstanceType {
    /// Runs continuously on hosts and responds to management requests from
    /// servers and clients.
    Agent,

    /// User interface for managing instances in the Sandpolis network.
    Client,

    /// Runs continously and coordinates interactions among instances in a
    /// Sandpolis network. All networks include at least one server
    /// instance.
    Server,
    // Probes are not technically instances, but they can connect to proper
    // agents/server instances and appear like standalone instances.
}

impl InstanceType {
    /// Each instance type has an identifier.
    pub const fn mask(&self) -> u8 {
        match self {
            InstanceType::Agent => 0b00000001,
            InstanceType::Client => 0b00000010,
            InstanceType::Server => 0b00000100,
        }
    }

    /// Each instance type has an associated color.
    pub const fn color(&self) -> colored::Color {
        match self {
            InstanceType::Agent => colored::Color::Cyan,
            InstanceType::Client => colored::Color::Green,
            InstanceType::Server => colored::Color::Magenta,
        }
    }
}

/// Names a capability a user can be granted, written as `"layer:action"`.
///
/// Permissions are granted layer-by-layer: `"shell:session"` allows opening
/// shell sessions, `"shell:*"` allows everything the shell layer offers, and
/// the bare wildcard `"*"` grants everything (there is no separate admin flag).
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(try_from = "String", into = "String")]
pub struct Permission {
    layer: String,
    action: String,
}

impl Permission {
    /// Whether this grant covers the given required permission.
    pub fn grants(&self, required: &Permission) -> bool {
        if self.layer == "*" {
            return true;
        }
        self.layer == required.layer && (self.action == "*" || self.action == required.action)
    }

    pub fn layer(&self) -> &str {
        &self.layer
    }

    pub fn action(&self) -> &str {
        &self.action
    }
}

impl FromStr for Permission {
    type Err = anyhow::Error;

    fn from_str(s: &str) -> Result<Self> {
        if s == "*" {
            return Ok(Self {
                layer: "*".to_string(),
                action: "*".to_string(),
            });
        }

        let Some((layer, action)) = s.split_once(':') else {
            bail!("invalid permission {s:?}: expected \"layer:action\" or \"*\"");
        };

        if layer.is_empty() || !layer.chars().all(|c| c.is_ascii_lowercase()) {
            bail!("invalid permission layer in {s:?}");
        }
        if action.is_empty()
            || !(action == "*"
                || action
                    .chars()
                    .all(|c| c.is_ascii_lowercase() || c == '_'))
        {
            bail!("invalid permission action in {s:?}");
        }

        Ok(Self {
            layer: layer.to_string(),
            action: action.to_string(),
        })
    }
}

impl TryFrom<String> for Permission {
    type Error = anyhow::Error;

    fn try_from(value: String) -> Result<Self> {
        value.parse()
    }
}

impl From<Permission> for String {
    fn from(value: Permission) -> Self {
        value.to_string()
    }
}

impl Display for Permission {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        if self.layer == "*" {
            f.write_str("*")
        } else {
            write!(f, "{}:{}", self.layer, self.action)
        }
    }
}

#[cfg(test)]
mod test_permission {
    use super::*;

    #[test]
    fn test_parse() {
        assert!("shell:session".parse::<Permission>().is_ok());
        assert!("shell:*".parse::<Permission>().is_ok());
        assert!("*".parse::<Permission>().is_ok());
        assert!("agent:power_off".parse::<Permission>().is_ok());

        assert!("".parse::<Permission>().is_err());
        assert!("shell".parse::<Permission>().is_err());
        assert!("shell:".parse::<Permission>().is_err());
        assert!(":session".parse::<Permission>().is_err());
        assert!("Shell:session".parse::<Permission>().is_err());
        assert!("shell:Session".parse::<Permission>().is_err());
        assert!("shell:session:extra".parse::<Permission>().is_err());
        assert!("*:session".parse::<Permission>().is_err());
    }

    #[test]
    fn test_grants() {
        let session: Permission = "shell:session".parse().unwrap();
        let execute: Permission = "shell:execute".parse().unwrap();

        assert!(session.grants(&session));
        assert!(!session.grants(&execute));

        let layer: Permission = "shell:*".parse().unwrap();
        assert!(layer.grants(&session));
        assert!(layer.grants(&execute));
        assert!(!layer.grants(&"desktop:session".parse().unwrap()));

        let all: Permission = "*".parse().unwrap();
        assert!(all.grants(&session));
        assert!(all.grants(&"desktop:session".parse().unwrap()));
    }

    #[test]
    fn test_round_trip() {
        for s in ["shell:session", "shell:*", "*"] {
            assert_eq!(s.parse::<Permission>().unwrap().to_string(), s);
        }
    }
}

/// Names a _layer_: the GUI face a subsystem presents, which the client's layer
/// picker chooses between and which notifications and services are attributed
/// to. A subsystem provides at most one, so the layer's name is the subsystem's
/// name (e.g. `"Shell"`, `"Inventory"`).
///
/// Layers are registered at runtime using the `inventory` crate.
#[cfg_attr(feature = "client", derive(bevy::prelude::Resource))]
#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize)]
pub struct LayerName(pub String);

impl LayerName {
    /// Create a new layer with the given name.
    pub const fn new(name: String) -> Self {
        Self(name)
    }

    /// Get the layer name.
    pub fn name(&self) -> &str {
        &self.0
    }

    /// Iterate over all registered layers.
    pub fn registered() -> impl Iterator<Item = &'static LayerName> {
        inventory::iter::<LayerName>()
    }
}

impl std::fmt::Display for LayerName {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.0)
    }
}

impl std::ops::Deref for LayerName {
    type Target = str;

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl From<&str> for LayerName {
    fn from(s: &str) -> Self {
        Self(s.to_string())
    }
}

impl From<String> for LayerName {
    fn from(s: String) -> Self {
        Self(s)
    }
}

impl PartialEq<str> for LayerName {
    fn eq(&self, other: &str) -> bool {
        self.0 == other
    }
}

impl PartialEq<&str> for LayerName {
    fn eq(&self, other: &&str) -> bool {
        self.0 == *other
    }
}

// Register LayerName with inventory for runtime collection
inventory::collect!(LayerName);

#[data(defaults)]
pub struct InstanceManagerData {
    pub cluster_id: ClusterId,
    /// The instance this row describes — also this row's owning scope, so a
    /// server can own exactly the identity rows of the instances attached to it.
    #[secondary_key]
    pub _instance_id: InstanceId,
    pub os_info: os_info::Info,
}

// Scoped by the instance the record describes, so a local stratum server can
// subscribe to just the instances connected to it. Without this the set of known
// instances never replicates at all and every peer looks empty.
inventory::submit! {
    crate::database::sync::SyncRegistration(
        |r| r.register_scoped::<InstanceManagerData>(|d| d._instance_id))
}

/// The sync `model_id` for [`InstanceManagerData`], used by clients to subscribe to
/// the set of known instances.
pub fn instance_manager_model_id() -> u32 {
    use native_model::Model;
    <InstanceManagerData as Model>::native_model_id()
}

#[derive(Clone)]
#[cfg_attr(feature = "client", derive(bevy::prelude::Resource))]
pub struct InstanceManager {
    /// Every domain in the estate. Assigned by the global stratum server and
    /// replicated from there, so this is a read-only view everywhere else.
    domains: ResidentVec<DomainData>,
    /// Every instance in the estate, replicated in. The client's world view is
    /// drawn from this, so it covers instances this one never talks to.
    instances: ResidentVec<InstanceManagerData>,
    /// The default realm, so callers that need one (the service runner, say)
    /// don't have to be handed the whole [`DatabaseManager`].
    realm: crate::database::RealmDatabase,
    pub instance_id: InstanceId,
    pub cluster_id: ClusterId,
}

impl InstanceManager {
    /// `instance_type` is what this process was started as, which is what its
    /// identity says about it forever after.
    pub async fn new(database: DatabaseManager, instance_type: InstanceType) -> Result<Self> {
        let realm = database.realm(RealmName::default())?;

        // The identity row is generated on first start and reused forever after.
        // It is seeded as instance-local bookkeeping rather than through the
        // scope gate: the row's own scope is this instance's id, which isn't
        // known until the row exists.
        {
            let r = realm.r_transaction()?;
            let existing = r
                .scan()
                .primary::<InstanceManagerData>()?
                .all()?
                .next()
                .transpose()?;
            drop(r);

            if existing.is_none() {
                let rw = realm.local_write()?;
                rw.insert(InstanceManagerData::scoped(InstanceId::random(
                    instance_type,
                )))?;
                rw.commit()?;
            }
        }

        let data: Resident<InstanceManagerData> = realm
            .resident_with((), || {
                InstanceManagerData::scoped(InstanceId::random(instance_type))
            })?;

        let instance_id = data.read()._instance_id;

        // A data directory belongs to the instance that created it. Running a
        // different instance against it would mean two instances sharing one
        // identity, which is exactly what this identity exists to prevent.
        if !instance_id.is_type(instance_type) {
            bail!(
                "This data directory belongs to a {:?} instance ({instance_id}), \
                 so a {instance_type:?} cannot run against it. Give each instance \
                 its own --data directory.",
                instance_id.instance_type()
            );
        }

        // With scoped authority, the self scope becomes writable from here on.
        if let Some(table) = database.authority().scope_table() {
            table.set_self(instance_id);
        }

        // Every subsystem raises notifications through a process-wide handle, so it
        // is installed here — the first point that knows both the database and
        // this instance's id. Idempotent, since startup builds an `InstanceManager`
        // more than once.
        crate::notification::install(&realm, instance_id);

        Ok(Self {
            instance_id,
            cluster_id: { data.read().cluster_id },
            domains: realm.resident_vec(())?,
            instances: realm.resident_vec(())?,
            realm,
        })
    }

    /// What this process is: agent, client, or server.
    pub fn instance_type(&self) -> InstanceType {
        self.instance_id.instance_type()
    }

    /// The domain the given instance belongs to, if any.
    ///
    /// Servers are never members, so the rule is applied here too: a server that
    /// somehow appears in a domain's member list still resolves to nothing.
    pub fn domain_of(&self, id: InstanceId) -> Option<String> {
        if !id.is_domain_member() {
            return None;
        }

        self.domains.iter().find_map(|domain| {
            let domain = domain.read();
            domain
                .members
                .contains(&id)
                .then(|| domain.name.trim().to_string())
                .filter(|name| !name.is_empty())
        })
    }

    /// Every domain in the estate.
    pub fn domains(&self) -> &ResidentVec<DomainData> {
        &self.domains
    }

    /// Every instance the estate knows about, this one included.
    ///
    /// A client draws a node per entry, which is how an agent it holds no
    /// connection to shows up at all.
    pub fn instances(&self) -> &ResidentVec<InstanceManagerData> {
        &self.instances
    }

    /// This instance's default realm.
    pub fn realm(&self) -> &crate::database::RealmDatabase {
        &self.realm
    }
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct LayerVersion {
    pub major: u32,
    pub minor: u32,
    pub patch: u32,
    pub description: Option<String>,
    // pub rev: Option<String>,
    // pub build_time: Option<String>,
}

impl TryFrom<String> for LayerVersion {
    type Error = anyhow::Error;

    /// Parse `major.minor.patch` with an optional `-description` suffix, which
    /// is the shape cargo's `CARGO_PKG_VERSION` takes.
    fn try_from(value: String) -> Result<Self, Self::Error> {
        let (numbers, description) = match value.split_once('-') {
            Some((numbers, description)) => (numbers, Some(description.to_string())),
            None => (value.as_str(), None),
        };

        let mut parts = numbers.split('.');
        let mut number = |field: &str| -> Result<u32, Self::Error> {
            parts
                .next()
                .ok_or_else(|| anyhow::anyhow!("missing {field} version in: {value}"))?
                .parse()
                .map_err(|_| anyhow::anyhow!("invalid {field} version in: {value}"))
        };

        let major = number("major")?;
        let minor = number("minor")?;
        let patch = number("patch")?;

        if parts.next().is_some() {
            anyhow::bail!("trailing version component in: {value}");
        }

        Ok(Self {
            major,
            minor,
            patch,
            description,
        })
    }
}

impl PartialOrd for LayerVersion {
    fn partial_cmp(&self, other: &Self) -> Option<Ordering> {
        Some(self.cmp(other))
    }
}

impl Ord for LayerVersion {
    fn cmp(&self, other: &Self) -> Ordering {
        if self.major > other.major {
            Ordering::Greater
        } else if self.major < other.major {
            Ordering::Less
        } else if self.minor > other.minor {
            Ordering::Greater
        } else if self.minor < other.minor {
            Ordering::Less
        } else if self.patch > other.patch {
            Ordering::Greater
        } else if self.patch < other.patch {
            Ordering::Less
        } else {
            Ordering::Equal
        }
    }
}

#[cfg(test)]
mod test_layer_version {
    use super::*;

    #[test]
    fn test_parse() {
        let version = LayerVersion::try_from("1.2.3".to_string()).unwrap();
        assert_eq!(version.major, 1);
        assert_eq!(version.minor, 2);
        assert_eq!(version.patch, 3);
        assert_eq!(version.description, None);
    }

    /// This crate's own version has to parse, since that's where these come
    /// from.
    #[test]
    fn test_parse_own_version() {
        LayerVersion::try_from(env!("CARGO_PKG_VERSION").to_string()).unwrap();
    }

    #[test]
    fn test_parse_with_description() {
        let version = LayerVersion::try_from("0.1.0-alpha.1".to_string()).unwrap();
        assert_eq!(version.major, 0);
        assert_eq!(version.minor, 1);
        assert_eq!(version.patch, 0);
        assert_eq!(version.description.as_deref(), Some("alpha.1"));
    }

    #[test]
    fn test_parse_rejects_malformed() {
        for value in ["", "1", "1.2", "1.2.3.4", "1.2.x", "v1.2.3", "-1.2.3"] {
            assert!(
                LayerVersion::try_from(value.to_string()).is_err(),
                "expected {value} to be rejected"
            );
        }
    }

    /// Ordering ignores the description, so a prerelease and its release
    /// compare equal.
    #[test]
    fn test_ordering() {
        let older = LayerVersion::try_from("1.2.3".to_string()).unwrap();
        let newer = LayerVersion::try_from("1.3.0".to_string()).unwrap();
        assert!(newer > older);
        assert!(older < LayerVersion::try_from("2.0.0".to_string()).unwrap());
        assert_eq!(
            older.cmp(&LayerVersion::try_from("1.2.3-alpha".to_string()).unwrap()),
            Ordering::Equal
        );
    }
}
