// This source file was automatically generated by the Sandpolis codegen plugin.
package com.sandpolis.core.instance.state.converter;

import java.util.function.Function;

import javax.persistence.AttributeConverter;
import javax.persistence.Converter;

import com.sandpolis.core.foundation.Platform;

@Converter
public class OsTypeConverter implements AttributeConverter<Platform.OsType, Integer> {
	public static final OsTypeConverter INSTANCE = new OsTypeConverter();

	public static final Function<Platform.OsType, Integer> SERIALIZER = INSTANCE::convertToDatabaseColumn;

	public static final Function<Integer, Platform.OsType> DESERIALIZER = INSTANCE::convertToEntityAttribute;

	@Override
	public Integer convertToDatabaseColumn(Platform.OsType value) {
		return value.getNumber();
	}

	@Override
	public Platform.OsType convertToEntityAttribute(Integer value) {
		return Platform.OsType.forNumber(value);
	}
}
