[package]
name = "com-sandpolis-agent-micro"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "agent"
path = "src/main/rust/main.rs"

[dependencies]
anyhow = "1.0"
env_logger = "0.8"
log = "0.4"
predicates = "2.0.0"
protobuf = { version = "3.0.0-alpha", features = ["with-bytes"] }
rust-embed = "5.9"
rustls = "0.19.0"
uuid = { version = "0.8", features = ["v4"] }
webpki-roots = "0.21"
webpki = "0.21.4"
