// This source file was automatically generated by the Sandpolis codegen plugin.
package com.sandpolis.core.instance.converter;

import com.sandpolis.core.instance.Metatypes;

import java.util.function.Function;

import javax.persistence.AttributeConverter;
import javax.persistence.Converter;

@Converter
public class InstanceTypeConverter implements AttributeConverter<Metatypes.InstanceType, Integer> {
	public static final InstanceTypeConverter INSTANCE = new InstanceTypeConverter();

	public static final Function<Metatypes.InstanceType, Integer> SERIALIZER = INSTANCE::convertToDatabaseColumn;

	public static final Function<Integer, Metatypes.InstanceType> DESERIALIZER = INSTANCE::convertToEntityAttribute;

	@Override
	public Integer convertToDatabaseColumn(Metatypes.InstanceType value) {
		return value.getNumber();
	}

	@Override
	public Metatypes.InstanceType convertToEntityAttribute(Integer value) {
		return Metatypes.InstanceType.forNumber(value);
	}
}
