// This source file was automatically generated by the Sandpolis codegen plugin.
package com.sandpolis.core.instance.converter;

import java.util.function.Function;

import com.sandpolis.core.foundation.Platform;

public class OsTypeConverter {
	public static final OsTypeConverter INSTANCE = new OsTypeConverter();

	public static final Function<Platform.OsType, Integer> SERIALIZER = INSTANCE::convertToDatabaseColumn;

	public static final Function<Integer, Platform.OsType> DESERIALIZER = INSTANCE::convertToEntityAttribute;

	public Integer convertToDatabaseColumn(Platform.OsType value) {
		return value.getNumber();
	}

	public Platform.OsType convertToEntityAttribute(Integer value) {
		return Platform.OsType.forNumber(value);
	}
}
