on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: "Build on ubuntu-latest"
    runs-on: ubuntu-latest
    steps:
      - name: Initialize QEMU
        uses: docker/setup-qemu-action@v1

      - name: Initialize buildx
        uses: docker/setup-buildx-action@v1

      - name: Initialize Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions-rs/install@v0.1
        with:
          crate: cross
          version: latest

      - name: Initialize Java
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Execute build
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: build --no-daemon
