on:
  push:
    tags:
      - "*"

jobs:
  publish:
    name: Publish release
    runs-on: ubuntu-latest
    steps:
      - name: Initialize QEMU
        uses: docker/setup-qemu-action@v1

      - name: Initialize buildx
        uses: docker/setup-buildx-action@v1

      - name: Initialize Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions-rs/install@v0.1
        with:
          crate: cross
          version: latest

      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Publish release
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: publish --no-daemon
        env:
          SIGNING_PGP_KEY: ${{ secrets.SIGNING_PGP_KEY }}
          SIGNING_PGP_PASSWORD: ${{ secrets.SIGNING_PGP_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
