#cargo-features = ["strip"]

[package]
name = "deployer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
env_logger = "0.8"
log = "0.4"
reqwest = { version = "0.11", default-features = false, features = ["blocking", "rustls-tls"] }
rust-embed = { version = "6.2", default-features = false, features = ["debug-embed"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
which = "4.2.2"

#[profile.release]
#strip = "symbols"
