[package]
name = "sandpolis-database"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
serde_cbor = { workspace = true }
serde = { workspace = true }
sled = { version = "0.34.7" }
tracing = { workspace = true }
tempfile = { workspace = true }
sandpolis-instance = { path = "../sandpolis-instance" }
