[package]
name = "sandpolis-database"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
serde_cbor = "0.11.2"
serde = { workspace = true }
sled = { version = "0.34.7" }
tracing = { workspace = true }
sandpolis-instance = { path = "../sandpolis-instance" }
