[package]
description = "Virtual estate monitoring & management!"
edition = "2024"
license = "AGPL-3.0-only"
name = "sandpolis-alert"
version = "0.0.1"

[dependencies]
anyhow = { workspace = true }

[features]
server = []
agent = []
client = []
