// This source file was automatically generated by the Sandpolis codegen plugin.
package com.sandpolis.core.instance.state;

import javax.persistence.AttributeConverter;
import javax.persistence.Converter;

@Converter
public class OidConverter implements AttributeConverter<Oid<?>, String> {
	@Override
	public String convertToDatabaseColumn(Oid<?> value) {
		return value.toString();
	}

	@Override
	public Oid<?> convertToEntityAttribute(String value) {
		return new Oid<>(value);
	}
}
