//============================================================================//
//                                                                            //
//                Copyright © 2015 - 2020 Subterranean Security               //
//                                                                            //
//  This source file is subject to the terms of the Mozilla Public License    //
//  version 2. You may not use this file except in compliance with the MPL    //
//  as published by the Mozilla Foundation at:                                //
//                                                                            //
//    https://mozilla.org/MPL/2.0                                             //
//                                                                            //
//=========================================================S A N D P O L I S==//
package com.sandpolis.gradle.codegen.document

import static javax.lang.model.element.Modifier.*

import com.squareup.javapoet.AnnotationSpec
import com.squareup.javapoet.ClassName
import com.squareup.javapoet.FieldSpec
import com.squareup.javapoet.JavaFile
import com.squareup.javapoet.MethodSpec
import com.squareup.javapoet.ParameterizedTypeName
import com.squareup.javapoet.TypeSpec

/**
 * Generator for JavaFX document bindings.
 */
class JavaFxDocumentBindingsGenerator extends DocumentBindingsGenerator {

	void processAttribute(parent, attribute) {

		if (attribute.type.endsWith("[]")) {
			// TODO ArrayAttribute
			return
		}

		def propertyType = ClassName.bestGuess("javafx.beans.property.${attribute.type}Property")

		// Add property field
		def propertyField = FieldSpec.builder(propertyType, attribute.name, PRIVATE)
			.initializer("new \$T()", ClassName.bestGuess("javafx.beans.property.Simple${attribute.type}Property"))
		parent.addField(propertyField.build())

		// Add property getter
		def propertyGetter = MethodSpec.methodBuilder(camel(attribute.name + "_property")).returns(propertyType)
			.addStatement("return ${attribute.name}").addModifiers(PUBLIC)
		parent.addMethod(propertyGetter.build())
	}

	void processDocument(parent, document) {

		def documentClass = TypeSpec.classBuilder(document.name).addModifiers(PUBLIC)

		if (document.collections != null) {
			for (def subcollection : document.collections) {
				processCollection("${parent}.0.${document.tag}", subcollection)
			}
		}
		if (document.documents != null) {
			for (def subdocument : document.documents) {
				processDocument("${parent}.${document.tag}", subdocument)
			}
		}
		if (document.attributes != null) {
			for (def subattribute : document.attributes) {
				processAttribute(documentClass, subattribute)
			}
		}

		JavaFile.builder(project.name, documentClass.build())
			.addFileComment("This source file was automatically generated by the Sandpolis codegen plugin.")
			.skipJavaLangImports(true).build().writeTo(project.file("gen/main/java"));
	}
}
